### ISSUE TITLE
Notifications broken (again)

### ISSUE THREAD

**Issue by archer-65** [xzz53/mu4e-alert#9] opened 2022-06-15 00:32 UTC
After a few months, notifications are problematic again.
When Emacs is started, then I receive a bunch of notifications, after that, no notifications, never.

```
(leaf mu4e-alert
  :doc "Enable notifications for mu4e"
  :straight (t :type git :host github :repo "xzz53/mu4e-alert")
  :after mu4e
  :init
  (mu4e-alert-set-default-style 'libnotify)
  (add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
  (setq mu4e-alert-notify-repeated-mails nil))
```

I'm currently using mu4e-alert like this, suggestions?

**Comment by xzz53** [comment] 2022-06-15 12:15
Hi! What version of `mu4e` and `emacs` do you use?

PS
I'm not sure whether semantics of `leaf` matches that of `use-package`, but could you try putting configuration under `:config`, like
```
:config
  (mu4e-alert-set-default-style 'libnotify)
  (mu4e-alert-enable-notifications)
```
?

**Comment by archer-65** [comment] 2022-06-15 13:21
> Hi! What version of `mu4e` and `emacs` do you use?
> 
> PS I'm not sure whether semantics of `leaf` matches that of `use-package`, but could you try putting configuration under `:config`, like
> 
> ```
> :config
>   (mu4e-alert-set-default-style 'libnotify)
>   (mu4e-alert-enable-notifications)
> ```
> 
> ?

Semantics is similar, especially for `:config`.
I've tried your snippet, nothing changed.

Here my `mu4e` configuration (excluded contexts), maybe it can be useful:

```
(leaf mu4e
  :require t
  :config

  ;; Use mu4e for sending e-mail
  (setq mail-user-agent 'mu4e-user-agent)

  ;; Needed? I don't know
  ;; (setq sendmail-program "/usr/bin/msmtp")
  (setq message-sendmail-f-is-evil t)
  (setq message-sendmail-extra-arguments '("--read-envelope-from"))
  (setq send-mail-function 'smtpmail-send-it)
  (setq message-send-mail-function 'message-send-mail-with-sendmail)
  ;; (setq mu4e-compose-signature "Sent from Emacs")

  ;; Contrib
  (require 'mu4e-contrib)

  (setq shr-color-visible-luminance-min 60)
  (setq shr-color-visible-distance-min 5)
  (setq shr-use-colors nil)
  (advice-add #'shr-colorize-region :around (defun shr-no-colourise-region (&rest ignore)))

  ;; Load org-mode integration
  (require 'org-mu4e)

  ;; This is set to 't' to avoid mail syncing issues when using mbsync
  (setq mu4e-change-filenames-when-moving t)

  ;; Refresh mail using isync every 10 minutes
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-update-interval (* 5 60))
  (setq mu4e-maildir "~/mails")
  (setq mu4e-main-buffer-hide-personal-addresses t)

  ;; Set Bookmarks for all
  (setq  mu4e-bookmarks '(( :name  "Unread messages"
                            :query "flag:unread AND NOT flag:trashed"
                            :key ?u)
                          ( :name "Today's messages"
                            :query "date:today..now"
                            :key ?t)))

  (setq mu4e-context-policy 'pick-first)

  ;; don't keep message buffers around
  (setq message-kill-buffer-on-exit t)

  ;; Don't ask to quit... why is this the default?
  (setq mu4e-confirm-quit nil)

  (mu4e t))
```

**Comment by xzz53** [comment] 2022-06-15 14:38
Thanks for the info! In order to reproduce this locally, I also need the value of `mu4e-mu-version`, and the git commit of `mu4e-alert` you use (it should be the last one, but just in case..). Btw, it's not mandatory to use `straight` for `mu4e-alert` now, since MELPA recipe points to this repo.

> When Emacs is started, then I receive a bunch of notifications

Are those notifications for the emails matching `mu4e-alert-interesting-mail-query` (`"flag:unread AND NOT flag:trashed"` by default), or completely irrelevant? The first option is the intended behaviour.

>after that, no notifications, never.

That's weird. Please check the value of `mu4e-index-updated-hook`. I'd also suggest sending yourself a mail from another mail client (web for example), then running `mu-update-mail-and-index` manually, and evaluating `(mu4e-alert-notify-unread-mail-async)` after that. Does this change anything?

**Comment by archer-65** [comment] 2022-06-15 14:52
> Thanks for the info! In order to reproduce this locally, I also need the value of `mu4e-mu-version`, and the git commit of `mu4e-alert` you use (it should be the last one, but just in case..). Btw, it's not mandatory to use `straight` for `mu4e-alert` now, since MELPA recipe points to this repo.
> 
> > When Emacs is started, then I receive a bunch of notifications
> 
> Are those notifications for the emails matching `mu4e-alert-interesting-mail-query` (`"flag:unread AND NOT flag:trashed"` by default), or completely irrelevant? The first option is the intended behaviour.
> 
> > after that, no notifications, never.
> 
> That's weird. Please check the value of `mu4e-index-updated-hook`. I'd also suggest sending yourself a mail from another mail client (web for example), then running `mu-update-mail-and-index` manually, and evaluating `(mu4e-alert-notify-unread-mail-async)` after that. Does this change anything?

You're right, I forgot versions:
`GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0) on PGTK NativeComp branch` 
`mu (mail indexer/searcher) version 1.6.11`
`mu4e-alert-20220528.1923`

The mails at startup are right, they respect the hook.

I've tried sending myself a mail from another client (web, mobile), running `mu-update-mail-and-index` give me no result. Same for the evaluation of  `(mu4e-alert-notify-unread-mail-async)`.

`mu4e-index-updated-hook` has value `(mu4e-alert-notify-unread-mail-async)`

**Comment by xzz53** [comment] 2022-06-15 16:55
Well, I tried reproducing the problem using the same versions as you do and as similar config as possible (but using package-config instead of leaf), but everything worked fine for me. I have no other ideas at the moment, but if you create minimal self-contained `init.el` triggering the issue, I can investigate this further.

**Comment by archer-65** [comment] 2022-06-15 17:38
> Well, I tried reproducing the problem using the same versions as you do and as similar config as possible (but using package-config instead of leaf), but everything worked fine for me. I have no other ideas at the moment, but if you create minimal self-contained `init.el` triggering the issue, I can investigate this further.

Do you mean an `init.el` with only `mu4e` and `mu4e-alert`?

**Comment by xzz53** [comment] 2022-06-15 17:39
> Do you mean an init.el with only mu4e and mu4e-alert?

Exactly.

**Comment by archer-65** [comment] 2022-06-15 18:28
> > Do you mean an init.el with only mu4e and mu4e-alert?
> 
> Exactly.

Perfect.
I have removed any context, so you can copy-paste yours.
Note that I'm using MSMTP to send mails, maybe some options don't work for you.
```
(setq package-enable-at-startup t)

;; Initialize package sources
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(unless package-archive-contents
  (package-refresh-contents))

;; <leaf-install-code>
(eval-and-compile
  (unless (package-installed-p 'leaf)
    (package-refresh-contents)
    (package-install 'leaf))

  (leaf leaf-keywords
    :ensure t
    :config
    ;; initialize leaf-keywords.el
    (leaf-keywords-init)))
;; </leaf-install-code>

(leaf mu4e
  :require t
  :commands mu4e mu4e-compose-new
  :init
  (provide 'html2text)
  :config
  (require 'mu4e-contrib)

  ;; General
  (setq mu4e-get-mail-command "mbsync -a"
	;; Update every 5 minutes
	mu4e-update-interval (* 5 60)
	;; Images
	mu4e-view-show-images t
	mu4e-view-image-max-width 800
	;; Don't keep message buffers around
	message-kill-buffer-on-exit t
	;; Start with default context
	mu4e-context-policy 'pick-first
	mu4e-compose-context-policy 'ask-if-none
	;; Why confirm quit?
	mu4e-confirm-quit nil)

  ;; User agent
  (setq mail-user-agent 'mu4e-user-agent)

  ;; Use mu4e for sending e-mail
  (setq send-mail-function #'smtpmail-send-it
	message-sendmail-f-is-evil t
	message-sendmail-extra-arguments '("--read-envelope-from")
	message-send-mail-function 'message-send-mail-with-sendmail)

  ;; Mail settings
  (setq mu4e-maildir "~/mails"
	;; This is set to 't' to avoid mail syncing issues when using mbsync
	mu4e-change-filenames-when-moving t
	mu4e-main-buffer-hide-personal-addresses t)

  ;; Contexts here

  ;; Set Bookmarks for all
  (setq  mu4e-bookmarks '(( :name  "Unread messages"
                            :query "flag:unread AND NOT flag:trashed"
                            :key ?u)
                          ( :name "Today's messages"
                            :query "date:today..now"
                            :key ?t)))

  (mu4e t))

;; Notifications!
(leaf mu4e-alert
  :doc "Enable notifications for mu4e"
  :ensure t
  :after mu4e
  :config
  (mu4e-alert-set-default-style 'libnotify)
  (mu4e-alert-enable-notifications)
  (setq mu4e-alert-notify-repeated-mails nil))
``` 

Thank you for your time, anyway!

**Comment by xzz53** [comment] 2022-06-15 19:09
Ok, I've reproduced your issue using the above config and Emacs 28.1. Now give me some time, and it'll be sorted out. Thanks for your help in debugging this!

**Comment by xzz53** [comment] 2022-06-15 19:54
@archer-65, do you by any chance have more unread messages than `mu4e-alert-max-messages-to-process` (500 by default) matching `mu4e-alert-interesting-mail-query`? If that is the case, the latest commit (https://github.com/xzz53/mu4e-alert/commit/3c9af8c7994df0a1a4f0703552ea3beffb485ace) should fix the issue.

**Comment by archer-65** [comment] 2022-06-15 20:15
Yes, I do...
I'll try with the latest commit, thank you!

**Comment by archer-65** [comment] 2022-06-15 22:10
> @archer-65, do you by any chance have more unread messages than `mu4e-alert-max-messages-to-process` (500 by default) matching `mu4e-alert-interesting-mail-query`? If that is the case, the latest commit ([3c9af8c](https://github.com/xzz53/mu4e-alert/commit/3c9af8c7994df0a1a4f0703552ea3beffb485ace)) should fix the issue.

One good thing:
I've read all my mails, notifications work now.

One bad thing:
Before reading the mails, it didn't work 😢

**Comment by xzz53** [comment] 2022-06-19 15:32
Please double-check you are running the latest `mu4e-alert` commit. I have just tested the case with over 500 unread messages on `emacs` 29.0.50 + `mu4e` 1.6.11 + `mu4e-alert` master and the configuration you provided, and notifications work as expected.

**Comment by archer-65** [comment] 2022-06-19 16:39
> Please double-check you are running the latest `mu4e-alert` commit. I have just tested the case with over 500 unread messages on `emacs` 29.0.50 + `mu4e` 1.6.11 + `mu4e-alert` master and the configuration you provided, and notifications work as expected.

I'm on the latest commit, I've tried again and it's working!

**Comment by xzz53** [comment] 2022-06-19 16:43
Fine, closing this.

**Closed as completed by xzz53** 2022-06-19 16:43 UTC
