### ISSUE TITLE
mu4e-alert broken: false positive 'new' messages, sometimes won't load

### ISSUE THREAD

**Issue by sunox1** [xzz53/mu4e-alert#6] opened 2022-03-29 23:36 UTC
`mu 1.6.10`
`emacs 27.1, 27.2, 29.0.50`

Hello,

I see this is the version of mu4e-alert that MELPA uses. Thanks for taking this up! 

I just updated to the version posted to MELPA from the previous 2019-era version, and I'm experiencing a couple strange issues. 

1. I am getting all kinds of strange false-positive 'new' messages after calling `mu-update-mail-and-index`. I have 0 new messages, but after calling this function I will see a large number of 'new' messages. The number of 'new' messages, and the messages themselves falsely identified as 'new' fluctuates a bit, the former more than the latter. I see this in the modeline indicator, and I get a bunch of desktop notifications. 

2. On my one install mu4e-alert won't load at the moment. When I try to call `(mu4e-alert-enable-notifications)` it throws this error: `Error running timer ‘mu4e-alert--get-mu-unread-emails-1’: (void-function make-closure)`. 

Thanks. Please let me know if I can provide any other info.

**Comment by xzz53** [comment] 2022-03-30 12:01
Hi,

please provide exact Emacs version (i.e. as reported by `report-emacs-bug`, or branch/commit if building from git) and all of your `mu4e-alert`-related configuration, and I'll try to reproduce issue 1.

Concerning `(void-function make-closure)` troubles: have you tried deleting '*.elc' and byte-recompiling from scratch when switching emacs versions? There are [reports](https://www.reddit.com/r/emacs/comments/qbnrao/symbols_function_definition_is_void_makeclosure/?utm_source=share&utm_medium=web2x&context=3) that it may help in your case.

JFYI:
I'm running `Emacs 27.2` + `mu 1.6.10` + latest `mu4e-alert` and it works quite smoothly.

**Comment by xzz53** [comment] 2022-03-30 12:54
Some more info for your consideration: the core change since "2019-era version" is the way how unread messages are obtained. After mu update 1.6, it became impossible to do it by calling `mu` executable, because actual database information was available only to the dedicated `mu` instance inside `mu4e` (at least until that instance exits). So I had to hack into `mu4e`s internals and reuse that `mu` process for the needs of `mu4e-alert`. Unfortunately, proper synchronization was impossible to implements without even further modifying `mu4e` guts. I decided not to do that at the moment, because existing implementation worked for me and other users in 99.9% cases, and such modifications would be extremely dependent on undocumented `mu4e` APIs, which had no stability guarantees. I have filed a `mu4e` [RFE](https://github.com/djcb/mu/issues/2210), which could help here, but `mu` maintainer seems to be not very enthusiastic.

Now to your issue (1), it looks like there is a race condition between `mu4e-alert--get-mu-unread-emails-1` updating unread message list  and `mu4e` trying to execute `:find` query (e.g. listing contents of a maildir/bookmark) at the same. So it'll be very helpful if you also provide your `mu4e` configuration (without any personal data, of course). Any hooks are of special interest.

**Comment by sunox1** [comment] 2022-03-30 14:13
I'm seeing this on two machines:

**Machine 1**
```
Debian Sid
Emacs 27.1
mu 1.6.10
```

**Machine 2**
```
Gentoo
Emacs 27.2 & 29.0.50
mu 1.6.10
```

Both worked pre-update. 

My mu4e-alert--relevant config is pretty simple:

```
(mu4e-alert-enable-notifications)
(mu4e-alert-set-default-style 'libnotify)
```

I see this problem with the following mu4e config. I've included only one context because they all have the same basic format, and I don't believe it can be a reason for the problem anyway.

```
(use-package mu4e
  :defer t
  :init
  :config

  (mu4e-alert-enable-notifications)
  (mu4e-alert-set-default-style 'libnotify)
  (add-hook 'mu4e-compose-mode-hook #'(lambda () (auto-save-mode -1)))
  (start-process-shell-command "mu4einit" nil "parallel --will-cite mbsync -c /home/xxx/Mail/mbsyncrc ::: icloud carleton personal")

  (setq message-send-mail-function 'smtpmail-send-it
	send-mail-function    'smtpmail-send-it
	smtpmail-stream-type  'starttls
	smtpmail-smtp-service 587
	mu4e-maildir "/home/xxx/Maildir"
	mu4e-get-mail-command "parallel --will-cite mbsync -c /home/xxx/Mail/mbsyncrc ::: icloud carleton personal"
        ;; I use 'parallel', but I get the issue with plain old serial mbsync as well
	mu4e-view-show-images t
	mu4e-context-policy 'pick-first
	mu4e-headers-show-threads nil
        ;; I tried different values for the next two options
	mu4e-index-cleanup t
	mu4e-index-lazy-check nil
	mu4e-split-view 'vertical
	mu4e-headers-visible-columns 130
	mu4e-compose-dont-reply-to-self t
	mu4e-change-filenames-when-moving t
	mu4e-user-mail-address-list '("xxx@icloud.com" "xxx@gmail.com" "xxx@xxx.ca" "xxx@xxx.ca")
	message-citation-line-format "\nOn %a %d %b %Y at %I:%M %p, %f wrote:\n"
	message-citation-line-function 'message-insert-formatted-citation-line
	message-kill-buffer-on-exit t)
```
```

  (setq mu4e-contexts
	`( ,(make-mu4e-context
	     :name "icloud"
	     :enter-func (lambda () (mu4e-message "Entering Private context"))
	     :leave-func (lambda () (mu4e-message "Leaving Private context"))
	     ;; we match based on the contact-fields of the message
	     :match-func (lambda (msg)
			   (when msg 
			     (mu4e-message-contact-field-matches msg 
								 :to "xxx@icloud.com")))
	     :vars '( ( user-mail-address      . "xxx@icloud.com"  )
		      ( user-full-name         . "xxxx" )
		      (mu4e-sent-folder . "/icloud/Sent Messages")
		      (mu4e-trash-folder . "/icloud/Deleted Messages")
		      (mu4e-drafts-folder . "/icloud/Drafts")
		      (mu4e-inbox-folder . "/icloud/INBOX")
		      ( mu4e-compose-signature .
			'nil)
		      (smtpmail-smtp-user . "xxx@icloud.com")
		      (smtpmail-smtp-server . "smtp.mail.me.com")
		      (mu4e-current-context . "icloud")))
```

And yes, it looks like the second issue is triggered when I change emacs versions. I went to re-test 27.2 on gentoo and I got one error which was fixed by byte-compiling mu4e-alert, but then I get another saying that it can't find the make-closure function.

Side-note, when byte-compiling mu4e-alert.el I get the following Warning:

`mu4e-alert.el:558:1:Warning: the following functions are not known to be defined:
    x-window-property, x-change-window-property,
    x-delete-window-property`

Maybe this is just noise, but I thought I should mention anyway.

Thanks again, and please let me know if I can do anything else.

**Comment by sunox1** [comment] 2022-03-30 14:39
Another perhaps telling behaviour is that the mu4e-headers buffer now wants to show me only unread emails after I update and get notified about the false positives. Unless I have an actual new email I of course get an empty buffer. I am pretty sure this behaviour is also new.

**Comment by xzz53** [comment] 2022-03-30 16:28
Thanks for the info, I'll try to reproduce your situation. Meanwhile, you can try to disable `mu4e-alert` initialization in `mu4e`'s `:config`, and do it manually later. This can theoretically affect the issue.

**Comment by sunox1** [comment] 2022-03-30 17:12
I gave that a try and no effect. 

I have some rather strange pieces of information to share:

1. I am only getting this behaviour when syncing one of my accounts: an Exchange account with my university. 
2. Besides the false-positive notifications, the other tell-tale strange behaviour is the scroll bar in `mu4e-headers` starts out huge, and then gradually shrinks, indicating I guess that the buffer is being populated with new lines incrementally. This whole process takes less than a second.
3. Most strangely: I only get the symptoms (false-positive detection of unread emails, notifications, buffer refresh showing only unread messages, scroll bar shrinkage) under the following condition:
    - When the `mu4e-headers` window occupies more than 2/3 of the vertical space on my screen, and 1/2 of the horizontal space. 

What in the world...

Point 3 seems to have to do with the number of rows/columns visible in `mu4e-headers`. I suppose it's possible that it existed before and I just never noticed it?

I am using `sway` window manager, in case that matters.

**Comment by xzz53** [comment] 2022-03-30 17:28
This becoming really interesting :smile:. You can try setting `mu4e-debug` to `t` **before** loading `mu4e`, then all the exchange with `mu` will be available in `*mu4e-log*` buffer. Please post this logs with and without `mu4e-alert` enabled (snipping actual message data, of course).

**Comment by sunox1** [comment] 2022-03-30 17:35
I just edited out a comment that the behaviour depended on the floating/tiling status of the window, which I just removed as it's not true. Not sure if you saw that version or not.

I will try to do this asap. I might have to step away for a bit to do other stuff, but we will see.

**Comment by sunox1** [comment] 2022-03-30 17:51
When experiencing the problem syncing the Exchange account:
https://dpaste.com/AKU2ZTB55

When NOT experiencing the problem syncing another account:
https://dpaste.com/AW2QDDJH7

When NOT experiencing the problem syncing the Exchange account (basically shrink window) I get the same mu4e-log pattern as when experiencing the problem.

So a clear difference in pattern. The problematic Exchange logs seem to show the process finishing like it does in the normal case, but then it goes on to keep showing more emails. This latter batch might be the ones reported as 'unread'. I'm not sure how this behaviour compares to what you see when you get *actual* new email. I might try that out next and share.

Edit:

Ok so curiously, when I call the update function to sync an 'unproblematic' account that has a new message, I get exactly the same behaviour as when syncing the Exchange account, and it even seems to show the same messages (messages from the exchange account), even though I'm not syncing that account.

Could this be a caching issue or something? I re-indexed mu4e yesterday to try to fix it, which obviously didn't work. How weird...

Anyway that is all for now I think.

**Comment by xzz53** [comment] 2022-03-30 18:57
So we can see, that in the "problematic" case, `mu4e-alert` query (`(find :query "flag:unread AND NOT flag:trashed" <...>)` interrupts `mu4e`'s own query (`(find :query "date:7d..now" <...>)`), and the results of both queries are messed up. The question is, why didn't it bite me or anyone else for so long?

One hypothesis is that it's related to the `mu4e` contexts (I don't use them myself, so that code path is much less tested). Could you comment out `(advice-add #'mu4e-context-switch :around #'mu4e-alert--context-switch)` line in `mu4e-alert.el` and test  again?

If above doesn't help, we can try to find out why the patterns differ by printing `mu4e~proc-find` backtraces like this:
```elisp
(require 'mu4e-proc)
(defun bt (&rest _) (message "XXX mu4e~proc-find") (backtrace))
(advice-add #'mu4e~proc-find :before #'bt)
```
Just evaluate this fragment before starting `mu4e` in the "problematic" case, look for relevant backtraces in `*Messages*` buffer and post them here.

**Comment by sunox1** [comment] 2022-03-30 19:17
Ok, sounds like progress! I'm tied up for the next few hours but I'll do this asap.

**Comment by sunox1** [comment] 2022-03-30 21:30
Ok so commenting out the line in mu4e-alert.el (and then byte-compiling it) didn't have any effect.

I ran the fragment you posted and then updated in the "problematic" case, and here is the output:

```
[mu4e] Retrieving mail...done
[mu4e] Indexing... processed 2, updated 2
[mu4e] Indexing completed; processed 2, updated 2, cleaned-up 2
XXX mu4e~proc-find
  backtrace()
  bt("date:7d..now" nil :date descending 500 t t)
  apply(bt ("date:7d..now" nil :date descending 500 t t))
  mu4e~proc-find("date:7d..now" nil :date descending 500 t t)
  mu4e~headers-search-execute("date:7d..now" t)
  mu4e-headers-search("date:7d..now" nil nil t nil)
  mu4e-headers-rerun-search()
  mu4e~headers-maybe-auto-update()
  run-hooks(mu4e-index-updated-hook)
  mu4e-info-handler((:info index :status complete :processed 2 :updated 2 :cleaned-up 2))
  mu4e~proc-filter(#<process  *mu4e-proc*> "\37644\377(:info index :status running :processed 2 :upd...")

XXX mu4e~proc-find
  backtrace()
  bt("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil)
  apply(bt ("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil))
  mu4e~proc-find("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil)
  mu4e-alert--get-mu-unread-emails-1(mu4e-alert--email-processor)
  apply(mu4e-alert--get-mu-unread-emails-1 mu4e-alert--email-processor)
  timer-event-handler([t 25156 51914 7451 nil mu4e-alert--get-mu-unread-emails-1 (mu4e-alert--email-processor) nil 170000 nil])
```

For what it's worth, it seems that both 'blocks' of output following `XXX mu4e~proc-find` correspond to the strange behaviour I was seeing. Lines containing `date:7d..now` refer to fully repopulating the `mu4e-headers` buffer after update, and the lines containing `flag:unread AND NOT flag:trashed` refer to finally showing only unread (and not trashed) messages (i.e. an empty buffer). You don't see either of these in unproblematic cases.

And for reference, here is how an "unproblematic" case (syncing one non-Exchange account) looks:

```
[mu4e] Retrieving mail...done
[mu4e] Indexing... processed 0, updated 0
[mu4e] Indexing completed; processed 0, updated 0, cleaned-up 0
```

Quite a difference!

**Comment by xzz53** [comment] 2022-03-30 22:23
Ok, as far as I can see you have `mu4e-headers-auto-update` set to `t`, resulting in the first backtrace. It is triggered when both `mu4e-headers-auto-update` is `t` and there are changed/new messages reported. Could you try setting it to `nil` and retest? I hope it's the last test for today.

I'll try to find some time tomorrow to reproduce your setup as closely as possible, and it'll be the best if you prepare minimal `init.el` reproducing the issue.

BTW, thanks for the detailed info and quick feedback!

**Comment by sunox1** [comment] 2022-03-30 22:52
When I set `mu4e-headers-auto-update` to `nil` it still reports `processed 2, updated 2` as it did before, but no weird buffer refreshes. Here is the backtrace of `mu4e~proc-find`:

```
[mu4e] Retrieving mail...done
[mu4e] Indexing... processed 2, updated 2
[mu4e] Indexing completed; processed 2, updated 2, cleaned-up 2
XXX mu4e~proc-find
  backtrace()
  bt("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil)
  apply(bt ("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil))
  mu4e~proc-find("flag:unread AND NOT flag:trashed" nil :date nil 500 nil nil)
  mu4e-alert--get-mu-unread-emails-1(mu4e-alert--email-processor)
  apply(mu4e-alert--get-mu-unread-emails-1 mu4e-alert--email-processor)
  timer-event-handler([t 25156 57055 123427 nil mu4e-alert--get-mu-unread-emails-1 (mu4e-alert--email-processor) nil 472000 nil])
```

I'm happy to test stuff as long as it's useful. I'm trying to get more familiar with dev-y sorts of things and this has been educational for me.

I can work on a minimal init.el tonight.

**Comment by sunox1** [comment] 2022-03-30 23:52
Here is a minimal init.el:

```
(let ((default-directory  "/path/to/elpadir"))
  (normal-top-level-add-subdirs-to-load-path))
(require 'mu4e-alert)

(mu4e-alert-enable-notifications)
(mu4e-alert-enable-mode-line-display)
(mu4e-alert-set-default-style 'libnotify)

(setq mu4e-get-mail-command "mbsync -a")

(mu4e)
(switch-to-buffer mu4e)
```
Then call:
`emacs -q -l minimal.el`

And in emacs:
`C-c C-u`

And again, I only see issues when syncing the Exchange account. 

I'm also noticing now that the faux 'unread' emails I see in notifications depends on what messages are currently shown in `*mu4e-headers*`: I only ever get notifications for emails currently in `*mu4e-headers*` For some batches of emails I will get the strange buffer reload, but no faux 'unread' email notification, and no 'show only unread AND trashed emails' behaviour. Maybe only certain messages trigger the notifications?

Also, not sure if this is useful, but I can get faux notifications for emails that belong to accounts other than the problematic Exchange one.

**Comment by sunox1** [comment] 2022-03-31 02:03
Ok more weird news, but we are maybe getting closer.

My Maildir for the problematic account has all the usual stuff, plus an `Archives` folder, which contains a number of subfolders for years like `2016`, `2017`, etc. I think I had these auto-generated by Thunderbird or something back when I used to use that.

When I sync my 'problematic' Exchange account I exclude this directory, because it never changes so why bother looking. 

I tried deleting this directory from my Maildir, and voila, I can sync the problematic one in mu4e with no weird issues.

If I re-download the `Archives` directory (and its sub-directories) using the `mbsync` command (specifically the `-a` flag which syncs everything), when I `C-x C-u` the Exchange account, the problem returns.

Whether I call `mbsync problematic_acc_name` from the command line with or without the `Archives` folder present in the Maildir, the output of the command looks the exact same. This is of course normal behaviour, but this situation is so odd to me that I feel I should mention it anyway.

Why would the Maildir presence of a directory that is not being synced matter in any way, much less to `mu4e-alert`?

Edit: and if I change my mbsyncrc so that I do not separate the Archives directory into it's own channel, but instead sync it along with everything else in the Exchange account, I get no errors.

**Comment by sunox1** [comment] 2022-03-31 02:47
### So to try to summarize this messy situation, I see five cases:
(You can maybe ignore everything above)

Case 1:
  - `Archives` remote dir in separate mbsync channel
  - `Archives` local dir present in Maildir
  - Sync the 'main' (i.e. everything except `Archives`) channel 
**Result: weird mu4e~proc-find/notification problems**

Case 2:
  - `Archives` remote dir in separate mbsync channel
  - `Archives` local dir deleted from Maildir
  - Sync the 'main' channel 
**Result: no issues whatsoever**

Case 3:
  - `Archives` remote dir included in 'main' mbsync channel
  - `Archives` local dir present in Maildir
  - Sync the 'main' channel
**Result: no issues whatsoever**

Case 4:
- `Archives` remote dir not included in any mbsync channel
- `Archives` local dir present or absent in Maildir
- Sync the 'main' channel
**Result: no issues whatsoever**

Bonus case!
  - `Archives` remote dir in separate mbsync channel
  -  `Archives` local dir present in Maildir
  - Sync the '**archives**' channel
**Result: no issues whatsoever**

So there are only issues in Case 1: when `Archives` is given its own mbsync channel, and when `Archives` is synced to my local Maildir. I can even sync the 'archives' channel without issue. 

I'm sorry if this is confusing. I'm pretty confused too and just trying to document anything I can. If it no longer seems like a `mu4e-alert` issue to you please just let me know. Among many puzzling things, I don't get why `mu4e-alert` would be thrown off by Case 1 above, and why it would only start to become confused by it after the most recent updates.

**Comment by sunox1** [comment] 2022-03-31 03:43
It turns out that I was actually using `parallel` in my `mu4e-get-mail-command` all along. If I use mbsync in the usual serial way, I get no issues in Case 1 above. 

Again, it's odd that `parallel` is suddenly causing issues - and only in the very specific circumstance of Case 1 - but at least we have maybe finally honed in on the problem? I'm not sure if any of this is helpful to you.

**Comment by xzz53** [comment] 2022-03-31 11:07
So, I've implemented some quick'n'dirty code to avoid calling `mu4e~proc-find` when another query is in progress. I believe this should fix the issue. However, this is quite an intrusive change, and regressions may be introduced, so it lives in a separate [branch](https://github.com/xzz53/mu4e-alert/tree/wip-recursion-prevention) for now. Testing and feedback are welcome!

**Comment by sunox1** [comment] 2022-03-31 13:08
Awesome, thanks! I've got it installed now and so far so good: it works using `parallel` syncing all the usual channels. Should I post any issues encountered on the main issues page?

**Comment by xzz53** [comment] 2022-03-31 13:33
> Should I post any issues encountered on the main issues page?

If all of your issues are resolved by the latest fix, I believe you should not. `mu` author does not provide support for the issues concerning third-party extensions.

My plan now is to test the fix for a couple days, and merge it to master/melpa if no regressions surface. I'll post an update here so that you can switch to melpa version.

**Comment by sunox1** [comment] 2022-03-31 14:23
Ok sounds great. If I notice anything odd I suppose I will post it here, but hopefully that won't be needed! Hopefully the new fix doesn't make your job any harder.

**Closed as completed** 2022-04-02 11:55 UTC

**Comment by xzz53** [comment] 2022-04-02 14:11
@sunox1 Look like melpa has just picked up the [updated version](https://melpa.org/#/mu4e-alert).
